- Gemfile
- lib/puppet/parameter/netscaler_name.rb
- lib/puppet/property/netscaler_traffic_domain.rb
- lib/puppet/property/netscaler_truthy.rb
- lib/puppet/provider/netscaler.rb
- lib/puppet/provider/netscaler_server/rest.rb
- lib/puppet/provider/netscaler_service/rest.rb
- lib/puppet/type/netscaler_server.rb
- lib/puppet/type/netscaler_service.rb
- lib/puppet/util/network_device/netscaler.rb
- lib/puppet/util/network_device/netscaler/device.rb
- lib/puppet/util/network_device/netscaler/facts.rb
- lib/puppet/util/network_device/transport/netscaler.rb
- spec/acceptance/first_spec.rb
- spec/acceptance/nodesets/aws-single.yml
- spec/acceptance/nodesets/aws.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/dual.yml
- spec/acceptance/nodesets/ec2.yaml
- spec/acceptance/nodesets/local.yml
- spec/acceptance/nodesets/pe.yml
- spec/fixtures/lib/beaker/hypervisor/netscaler.rb
- spec/spec_helper_acceptance.rb
This adds the `netscaler_server` and `netscaler_service` resources, and beaker-rspec test ability.
> Initial work

- lib/puppet/property/netscaler_truthy.rb
Added ON and OFF to netscaler truthy code.
> Added ON and OFF to netscaler truthy code.

- spec/acceptance/lb_vserver.rb
Added basic acceptance test for lbvserver
> Added basic acceptance test for lbvserver

- lib/puppet/provider/netscaler.rb
Fix for destroy method regarding URI construction
> Fix for destroy method regarding URI construction

- lib/puppet/provider/netscaler_csvserver/rest.rb
- lib/puppet/type/netscaler_csvserver.rb
- spec/acceptance/csvserver.rb
> Initial code for csvserver

- lib/puppet/provider/netscaler_csvserver_responderpolicy_bind/rest.rb
- lib/puppet/type/netscaler_csvserver_responderpolicy_bind.rb
Initial code for netscaler_csvserver_responderpolicy_bind
> Initial code for netscaler_csvserver_responderpolicy_bind

- spec/acceptance/netscaler_csvserver_responderpolicy_bind.rb
Added basic acceptance test for netscaler_csvserver_responderpolicy_bind
> Added basic acceptance test for netscaler_csvserver_responderpolicy_bind

- lib/puppet/provider/netscaler_rewriteaction/rest.rb
- lib/puppet/provider/netscaler_rewritepolicy/rest.rb
- lib/puppet/type/netscaler_rewriteaction.rb
- lib/puppet/type/netscaler_rewritepolicy.rb
- spec/acceptance/netscaler_rewriteaction.rb
- spec/acceptance/netscaler_rewritepolicy.rb
Initial code for rewritepolicy and rewriteaction
> Initial code for rewritepolicy and rewriteaction

- lib/puppet/provider/netscaler_csvserver_rewritepolicy_bind/rest.rb
- lib/puppet/type/netscaler_csvserver_rewritepolicy_bind.rb
- spec/acceptance/netscaler_csvserver_rewritepolicy_bind.rb
Initial code for netscaler_csvserver_rewritepolicy_bind
> Initial code for netscaler_csvserver_rewritepolicy_bind

- lib/puppet/provider/netscaler_rewriteglobal/rest.rb
- lib/puppet/type/netscaler_rewriteglobal.rb
Initial code for rewrite global
> Initial code for rewrite global

- lib/puppet/type/netscaler_rewriteglobal.rb
- spec/acceptance/netscaler_rewriteglobal.rb
Added autorequire calls for rewriteglobal and added basic acceptance test for rewrite global
> Added autorequire calls for rewriteglobal and added basic acceptance test for rewrite global

- lib/puppet/provider/netscaler_csvserver/rest.rb
- lib/puppet/type/netscaler_csvserver.rb
Initial code for csvserver purge_bindings
> Initial code for csvserver purge_bindings

- lib/puppet/provider/netscaler_csvserver/rest.rb
- lib/puppet/type/netscaler_csvserver.rb
- spec/acceptance/netscaler_csvserver_lbvserver_bind.rb
Initial code for csvserver_lbvserver_bind (as a property to csvserver)
> Initial code for csvserver_lbvserver_bind (as a property to csvserver)

- lib/puppet/provider/netscaler_rewritepolicy/rest.rb
Fix for rewritepolicy mapping.
> Fix for rewritepolicy mapping.

- spec/fixtures/lib/beaker/hypervisor/netscaler.rb
Reverts puppetlabs/puppetlabs-netscaler#35
> Revert "Fix beaker connection reset errors"

- lib/puppet/provider/netscaler_rewriteaction/rest.rb
Styling fixes for netscaler_rewriteaction
> Styling fixes for netscaler_rewriteaction

- spec/acceptance/netscaler_csvserver_cspolicy_bind.rb
Initial test for netscaler_csvserver_cspolicy_bind
> Initial test for netscaler_csvserver_cspolicy_bind

- lib/puppet/provider/netscaler_csvserver_rewritepolicy_bind/rest.rb
- lib/puppet/type/netscaler_csvserver_rewritepolicy_bind.rb
- spec/acceptance/netscaler_csvserver_rewritepolicy_bind_spec.rb
Reimplemented choose_type for netscaler_csvserver_rewritepolicy_bind
> Reimplemented choose_type for netscaler_csvserver_rewritepolicy_bind

- lib/puppet/provider/netscaler_csvserver_responderpolicy_bind/rest.rb
- lib/puppet/type/netscaler_csvserver_responderpolicy_bind.rb
- spec/acceptance/netscaler_csvserver_responderpolicy_bind_spec.rb
Updated implementation for invoking a vserver in netscaler_csvserver_responderpolicy_bind
> Updated implementation for invoking a vserver in netscaler_csvserver_responderpolicy_bind

- lib/puppet/provider/netscaler_rewritepolicylabel/rest.rb
- lib/puppet/type/netscaler_rewritepolicylabel.rb
- spec/acceptance/netscaler_rewritepolicylabel_spec.rb
Initial code for netscaler_rewritepolicylabel
> Initial code for netscaler_rewritepolicylabel

- lib/puppet/provider/netscaler_rewriteglobal/rest.rb
- lib/puppet/type/netscaler_rewriteglobal.rb
- spec/acceptance/netscaler_rewriteglobal_spec.rb
Implemented new way of handling req/resvserver for rewrite global
> Implemented new way of handling req/resvserver for rewrite global

- lib/puppet/type/netscaler_csvserver.rb
- lib/puppet/type/netscaler_csvserver_rewritepolicy_bind.rb
Updated csvserver code to allow case-insensitivity for fixed values
> Updated csvserver code to allow case-insensitivity for fixed values

- lib/puppet/type/netscaler_lbvserver.rb
Updated lbvserver code to allow case-insensitivity for fixed values
> Updated lbvserver code to allow case-insensitivity for fixed values

- lib/puppet/type/netscaler_responderaction.rb
- lib/puppet/type/netscaler_responderpolicylabel.rb
Updated responder code to allow case-insensitivity for fixed values
> Updated responder code to allow case-insensitivity for fixed values

- lib/puppet/type/netscaler_rewriteaction.rb
- lib/puppet/type/netscaler_rewritepolicy.rb
- lib/puppet/type/netscaler_rewritepolicylabel.rb
Updated rewrite code to allow case-insensitivity for fixed values
> Updated rewrite code to allow case-insensitivity for fixed values

- lib/puppet/type/netscaler_cspolicylabel.rb
Updated cspolicylabel code to allow case-insensitivity for fixed values
> Updated cspolicylabel code to allow case-insensitivity for fixed values

- lib/puppet/type/netscaler_sslcert.rb
Updated ssl code to allow case-insensitivity for fixed values
> Updated ssl code to allow case-insensitivity for fixed values

- lib/puppet/type/netscaler_service.rb
- lib/puppet/type/netscaler_servicegroup.rb
Updated service code to allow case-insensitivity for fixed values
> Updated service code to allow case-insensitivity for fixed values

- lib/puppet/type/netscaler_lbmonitor.rb
Updated lbmonitor code to allow case-insensitivity for fixed values
> Updated lbmonitor code to allow case-insensitivity for fixed values

- lib/puppet/provider/netscaler.rb
Added code to not call set_state when we don't have a state to set.
Added code to set_state to handle a nil state.
> Added code to not call set_state when we don't have a state to set.

- spec/acceptance/netscaler_server_spec.rb
- spec/acceptance/netscaler_service_spec.rb
Initial server and service spec tests
> Initial server and service spec tests

- spec/acceptance/netscaler_csvserver_cspolicy_bind.rb
- spec/acceptance/netscaler_csvserver_lbvserver_bind_spec.rb
- spec/acceptance/netscaler_csvserver_responderpolicy_bind_spec.rb
- spec/acceptance/netscaler_csvserver_rewritepolicy_bind_spec.rb
- spec/acceptance/netscaler_csvserver_spec.rb
- spec/acceptance/netscaler_lbvserver_spec.rb
- spec/acceptance/netscaler_responderglobal_spec.rb
- spec/acceptance/netscaler_rewriteaction_spec.rb
- spec/acceptance/netscaler_rewriteglobal_spec.rb
- spec/acceptance/netscaler_rewritepolicy_spec.rb
- spec/acceptance/netscaler_rewritepolicylabel_spec.rb
Change IP addresses in tests, and rename resources
> Change IP addresses in tests, and rename resources

- lib/puppet/provider/netscaler_responderglobal/rest.rb
- spec/acceptance/netscaler_csaction_spec.rb
It doesn't fix the responderglobal not being able to change the priority, but that should be the only error.
> Fix failing beaker tests

- lib/puppet/type/netscaler_responderglobal.rb
Fixes for responderglobal dependancy issues
> Fixes for responderglobal dependancy issues

- lib/puppet/provider/netscaler_servicegroup/rest.rb
Made autoscale_mode immutable in servicegroup
> Made autoscale_mode immutable in servicegroup

- lib/puppet/provider/netscaler_lbmonitor/rest.rb
Added override for destory method in lbmonitor
> Added override for destory method in lbmonitor

- spec/acceptance/netscaler_servicegroup_spec.rb
Initial tests for servicegroup
> Initial tests for servicegroup

- spec/acceptance/netscaler_lbmonitor_spec.rb
> Initial test for lbmonitor

- spec/acceptance/netscaler_service_lbmonitor_bind_spec.rb
Initial test for service_lbmonitor_bind
> Initial test for service_lbmonitor_bind

- lib/puppet/provider/netscaler_servicegroup_lbmonitor_bind/rest.rb
- lib/puppet/type/netscaler_servicegroup_lbmonitor_bind.rb
Fixes for servicegroup_lbmonitor_bind regarding destroy and munging issues
> Fixes for servicegroup_lbmonitor_bind regarding destroy and munging issues

- spec/acceptance/netscaler_servicegroup_lbmonitor_bind_spec.rb
Initial test for servicegroup_lbmonitor_bind
> Initial test for servicegroup_lbmonitor_bind

- spec/acceptance/netscaler_servicegroup_member_spec.rb
Initial test for servicegroup_member
> Initial test for servicegroup_member

- spec/acceptance/netscaler_lbvserver_responderpolicy_bind_spec.rb
Initial test for lbvserver_responderpolicy_bind
> Initial test for lbvserver_responderpolicy_bind

- lib/puppet/provider/netscaler_lbvserver_service_bind/rest.rb
Fix for lbvserver_service_bind destroy issues
> Fix for lbvserver_service_bind destroy issues

- spec/acceptance/netscaler_lbvserver_service_bind_spec.rb
Initial test for lbvserver_service_bind
> Initial test for lbvserver_service_bind

- spec/acceptance/netscaler_lbvserver_responderpolicy_bind_spec.rb
Additional test for lbvserver_responderpolicy_bind
> Additional test for lbvserver_responderpolicy_bind

- lib/puppet/provider/netscaler_lbvserver_responderpolicy_bind/rest.rb
- lib/puppet/type/netscaler_lbvserver_responderpolicy_bind.rb
Req fixes for lbvserver_responderpolicy_bind
> Req fixes for lbvserver_responderpolicy_bind

- lib/puppet/provider/netscaler.rb
Fix for changing resource states. A further PR is required for the providers where flush_state_args needs overriden.
> Fix for changing resource states

- lib/puppet/provider/netscaler_service_lbmonitor_bind/rest.rb
- lib/puppet/type/netscaler_service_lbmonitor_bind.rb
Fixes for service_lbmonitor_bind idempotency and destroy issues. Also removing passive property.
> Fixes for service_lbmonitor_bind idempotency and destroy issues. Also removing passive property.

- lib/puppet/provider/netscaler_servicegroup/rest.rb
- spec/acceptance/netscaler_servicegroup_spec.rb
Added override to servicegroup to allow state changing to work. Also added code to account for non-existent autoscale value in get REST response.
> Added override to servicegroup to allow state changing to work. Also add.ed code to account for non-existent autoscale value in get REST response.

- spec/acceptance/netscaler_server_spec.rb
Added initial test for changing server state
> Added initial test for changing server state

- spec/acceptance/netscaler_service_spec.rb
> Service state change test

- lib/puppet/provider/netscaler_lbvserver/rest.rb
- spec/acceptance/netscaler_lbvserver_spec.rb
Test and code for lbvserver state change.
> Test and code for lbvserver state change.

- lib/puppet/provider/netscaler_csvserver/rest.rb
- spec/acceptance/netscaler_csvserver_spec.rb
Code and test for csverver state changing
> Code and test for csverver state changing

- spec/acceptance/netscaler_service_spec.rb
> Test fixes for service

- README.md
Adds README in templated format with first round deliverables documented.
> First round updates

- README.md
1.) Add template structure to README.
2.) Update TOC for NetScaler.
3.) Add Overview and  Module Description.
4.) Add first draft docs for Setup and Usage sections.
5.) Add netscaler_lbmonitor, netscaler_server, netscaler_service, netscaler_service_lbmonitor_bind type descriptions and parameter listings (with descriptions and valid options (and, where necessary, defaults).
> First deliverables final draft

- lib/puppet/provider/netscaler_sslcertkey/rest.rb
- lib/puppet/provider/netscaler_sslocspresponder/rest.rb
- lib/puppet/provider/netscaler_sslvserver/rest.rb
- lib/puppet/provider/netscaler_vlan_nsip_bind/rest.rb
- lib/puppet/type/netscaler_csvserver.rb
- lib/puppet/type/netscaler_sslcertkey.rb
- lib/puppet/type/netscaler_sslocspresponder.rb
- lib/puppet/type/netscaler_sslvserver.rb
- spec/acceptance/netscaler_sslcertkey_spec.rb
- spec/acceptance/netscaler_sslocspresponder_spec.rb
- spec/acceptance/netscaler_sslvserver_spec.rb
> adding vserver and certkey

- README.md
Readme fix as discussed at planning/standup.
> Fixup some example artifacts in NetScaler readme

- lib/puppet/type/netscaler_route.rb
Swapped DISABLED and ENABLED in the truthy_property of both msr and advertise
> (FM-2628) Update netscaler_route.rb

- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/ec2.yaml
Added NetScaler Platinum AMI to allow us to test more features
> Update ec2.yaml & default.yml to use Platinum NetScaler ami

- lib/puppet/provider/netscaler_lbvserver_rewritepolicy_binding/rest.rb
- lib/puppet/type/netscaler_lbvserver_rewritepolicy_binding.rb
Based off the responderpolicy_binding type, this type allows you to bind rewrite policies to a LB vserver.
> Added type and provider to bind rewrite policy to lb vserver.

- README.md
normalize setup of puppet agents used to run puppet device
correct markdown
> (DOC-1967) document puppet device
